// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ztltxmtctwptdcuztcze.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp0bHR4bXRjdHdwdGRjdXp0Y3plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyOTk3NDIsImV4cCI6MjA2Mzg3NTc0Mn0.I0incEvbdgzPip6qqzIduKfBxMqiz8CUdTIjzsPeKgk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);